services:
  postgres:
    image: postgres:18
    container_name: gc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gamingcastle
      POSTGRES_USER: gc_admin
      POSTGRES_PASSWORD: gc_password
    ports:
      - "5432:5432"
    volumes:
      - infra_pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: gc-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gamingcastle.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  infra_pgdata:
    external: true